packages:
  - 'packages/*'
  - 'packages/routing-sdk/**'
  - 'apps/*'
  - 'apis/*'
  - 'examples/*'
  - 'scripts'

catalog:
  '@aptos-labs/ts-sdk': 1.30.0
  '@next/eslint-plugin-next': 14.2.3
  '@solana/web3.js': 1.95.8
  '@types/react': ^18.2.21
  '@types/react-dom': ^18.0.6
  '@vanilla-extract/vite-plugin': ^4.0.2
  '@vercel/functions': 2.0.0
  eslint: ^8.32.0
  jotai: 2.12.5
  next: 15.2.3
  react: ^18.2.0
  react-dom: ^18.2.0
  viem: 2.31.3
  wagmi: ^2.15.5
  wrangler: 3.81.0
  zod: ^3.25.67