name: Unit Tests Pass

on:
  pull_request:
    paths:
      - 'locales/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node: [18]

    name: Unit tests (Jest)

    steps:
      - run: 'echo "Unit tests skipped"'
