name: Unit Tests

on:
  pull_request:
    paths-ignore:
      - 'locales/**'
  push:
    branches:
      - develop

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    strategy:
      fail-fast: true
      matrix:
        node: [18]

    name: Unit tests (Jest)

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install dependencies
        uses: './.github/actions/install-deps'

      - name: Run tests
        run: |
          pnpm test:ci
          if git diff --name-only HEAD^1 | grep -q '^apps/' && ! git diff --name-only HEAD^1 | grep -q '^apps/web/'; then
            cd apps/web && npx vitest run src/__tests__/translations.test.ts
          fi
